### ISSUE TITLE
Add the ability to give a CC in `send_mail_plus`

### ISSUE THREAD

**Issue by SilviaAmAm** [maykinmedia/mail-cleaner#2]
`EmailMessage` in django supports cc/bcc: https://docs.djangoproject.com/en/4.2/topics/email/#emailmessage-objects

`EmailMultiAlternatives` subclasses `EmailMessage`.

It would be nice to add the ability to specify the CC/BCC in this function: https://github.com/maykinmedia/mail-cleaner/blob/main/mail_cleaner/mail.py#L23 
(or *args, **kwargs)

**Comment by sergei-maertens** [comment]
Tag pushed, it's being released to PyPI
